fix race read while running proxy
galihrivanto/go-inkscape pull request #2
Opened 2021-02-11 10:34 UTC by euiko

Look like the #1 are caused by we are read the same buffer with the exec.Cmd are internally using to write the buffer,
In order to avoid race this PR just copy the buffer before pass it into chan for reading.

2021-02-12 03:01 UTC, galihrivanto requested changes
LGTM, works to prevent race condition
please address comment and its good to merge

2021-02-12 03:01 UTC, galihrivanto commented on proxy.go
> +	bufferToWrite := append([]byte{}, data...)
use `copy` instead of inline `append`

2021-02-15 07:24 UTC, euiko commented on proxy.go
> +	bufferToWrite := append([]byte{}, data...)
updated @galihrivanto using `copy`, feel free to review it

2021-02-15 07:26 UTC, merged

2021-02-15 07:26 UTC, galihrivanto commented
thank you